# Generated by Django 5.0.10 on 2025-06-17 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeBillStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Complete'), (3, 'Close'), (4, 'Delete')], unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Make Bill Status',
                'verbose_name_plural': 'Make Bill Statuses',
                'db_table': 'MakeBillStatus',
                'ordering': ['status_code'],
            },
        ),
        migrations.CreateModel(
            name='MakeBillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_number', models.CharField(max_length=20, verbose_name='OP Number')),
                ('opu_number', models.CharField(max_length=20, verbose_name='OPU Number')),
                ('edu_number', models.CharField(max_length=20, verbose_name='EDU Number')),
                ('model_name', models.CharField(max_length=100)),
                ('components', models.JSONField(blank=True, default=dict, null=True)),
                ('case_style_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Case Style Data')),
                ('can_details', models.JSONField(blank=True, default=dict, null=True)),
                ('pcb_details', models.JSONField(blank=True, default=dict, null=True)),
                ('chip_aircoil_details', models.JSONField(blank=True, default=dict, null=True)),
                ('chip_inductor_details', models.JSONField(blank=True, default=dict, null=True)),
                ('chip_capacitor_details', models.JSONField(blank=True, default=dict, null=True)),
                ('chip_resistor_details', models.JSONField(blank=True, default=dict, null=True)),
                ('transformer_details', models.JSONField(blank=True, default=dict, null=True)),
                ('shield_details', models.JSONField(blank=True, default=dict, null=True)),
                ('finger_details', models.JSONField(blank=True, default=dict, null=True)),
                ('copper_flaps_details', models.JSONField(blank=True, default=dict, null=True)),
                ('resonator_details', models.JSONField(blank=True, default=dict, null=True)),
                ('ltcc_details', models.JSONField(blank=True, default=dict, null=True)),
                ('special_requirements', models.JSONField(blank=True, default=dict, null=True)),
                ('revision_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='make_bill_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='make_bill_updated_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='make_bill_records', to='pibase_makebill.makebillstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Make Bill Record',
                'verbose_name_plural': 'Make Bill Records',
                'db_table': 'MakeBillRecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
