# Generated by Django 5.0.10 on 2025-06-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase_makebill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makebillrecord',
            name='pibaseRecord',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
