# Generated by Django 5.0.10 on 2025-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase_makebill', '0002_makebillrecord_pibaserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makebillrecord',
            name='special_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Special Requirements'),
        ),
    ]
