# Generated by Django 5.0.10 on 2025-05-21 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiBaseComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('format', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PiBaseComponent',
            },
        ),
        migrations.CreateModel(
            name='PiBaseFieldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('input_type', models.PositiveSmallIntegerField(choices=[(1, 'Dropdown'), (2, 'Radio Button')])),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PiBaseFieldCategory',
            },
        ),
        migrations.CreateModel(
            name='PiBaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Pending'), ('2', 'Complete'), ('3', 'Close'), ('4', 'Delete')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PiBaseStatus',
            },
        ),
        migrations.CreateModel(
            name='PiBaseFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pibase.pibasefieldcategory')),
            ],
            options={
                'db_table': 'PiBaseFieldOption',
            },
        ),
        migrations.CreateModel(
            name='PiBaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_no', models.CharField(max_length=20, verbose_name='OP Number')),
                ('opu_no', models.CharField(max_length=20, verbose_name='OPU Number')),
                ('edu_no', models.CharField(max_length=20, verbose_name='EDU Number')),
                ('model_name', models.CharField(max_length=100)),
                ('schematic', models.TextField(blank=True, null=True)),
                ('similar_model_layout', models.TextField(blank=True, null=True)),
                ('revision_number', models.CharField(max_length=20)),
                ('impedance_selection', models.JSONField(default=dict, verbose_name='Impedance Selection')),
                ('package_details', models.JSONField(blank=True, default=dict, null=True, verbose_name='Package Details')),
                ('case_style_data', models.JSONField(default=dict, verbose_name='Case Style Data')),
                ('can_details', models.JSONField(blank=True, default=dict, null=True)),
                ('pcb_details', models.JSONField(blank=True, default=dict, null=True)),
                ('aircoil_details', models.JSONField(blank=True, default=dict, null=True)),
                ('inductor_details', models.JSONField(blank=True, default=dict, null=True)),
                ('capacitor_details', models.JSONField(blank=True, default=dict, null=True)),
                ('resistor_details', models.JSONField(blank=True, default=dict, null=True)),
                ('transformer_details', models.JSONField(blank=True, default=dict, null=True)),
                ('shield_details', models.JSONField(blank=True, default=dict, null=True)),
                ('finger_details', models.JSONField(blank=True, default=dict, null=True)),
                ('copper_flaps_details', models.JSONField(blank=True, default=dict, null=True)),
                ('resonator_details', models.JSONField(blank=True, default=dict, null=True)),
                ('ltcc_details', models.JSONField(blank=True, default=dict, null=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottom_solder_mask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_bottom_solder_mask', to='pibase.pibasefieldoption', verbose_name='Bottom Solder Mask')),
                ('components', models.ManyToManyField(blank=True, related_name='devices', to='pibase.pibasecomponent')),
                ('cover_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_cover_type', to='pibase.pibasefieldoption', verbose_name='Cover Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_base_records', to=settings.AUTH_USER_MODEL)),
                ('design_rule_violation_accepted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_design_rule_violation_accepted', to='pibase.pibasefieldoption', verbose_name='Design Rule Violation Accepted')),
                ('half_moon_requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_half_moon_requirement', to='pibase.pibasefieldoption', verbose_name='Half Moon Requirement')),
                ('model_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_model_family', to='pibase.pibasefieldoption', verbose_name='Model Family')),
                ('signal_launch_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_signal_launch_type', to='pibase.pibasefieldoption', verbose_name='Signal Launch Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_base_records_updated', to=settings.AUTH_USER_MODEL)),
                ('via_holes_on_signal_pads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_via_holes_on_signal_pads', to='pibase.pibasefieldoption', verbose_name='Via Holes On Signal Pads')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_models', to='pibase.pibasestatus')),
            ],
            options={
                'verbose_name': 'PiBaseRecord',
                'verbose_name_plural': 'PiBaseRecords',
                'db_table': 'PiBaseRecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
