# Generated by Django 5.0.10 on 2025-05-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibaserecord',
            name='technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
