# Generated by Django 5.0.10 on 2025-05-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0002_pibaserecord_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pibaserecord',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_technology', to='pibase.pibasefieldoption', verbose_name='Technology'),
        ),
    ]
