# Generated by Django 5.0.10 on 2025-05-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0003_alter_pibaserecord_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibasecomponent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pibasecomponent',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class for the component, e.g., 'CircuitBoard'", max_length=100, null=True, unique=True),
        ),
    ]
