# Generated by Django 5.0.10 on 2025-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0004_pibasecomponent_description_pibasecomponent_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pibasecomponent',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class for the component, e.g., 'CircuitBoard'", max_length=100, null=True),
        ),
    ]
