# Generated by Django 5.0.10 on 2025-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0005_alter_pibasecomponent_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibaserecord',
            name='special_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Special Requirements'),
        ),
    ]
