# Generated by Django 5.0.10 on 2025-05-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0006_pibaserecord_special_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pibaserecord',
            name='schematic',
            field=models.FileField(blank=True, null=True, upload_to='schematics/'),
        ),
    ]
