# Generated by Django 5.0.10 on 2025-05-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pibase', '0007_alter_pibaserecord_schematic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pibaserecord',
            name='design_rule_violation_accepted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_design_rule_violation_accepted', to='pibase.pibasefieldoption', verbose_name='Design Rule Violation'),
        ),
        migrations.AlterField(
            model_name='pibaserecord',
            name='via_holes_on_signal_pads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_via_holes_on_signal_pads', to='pibase.pibasefieldoption', verbose_name='Via Holes Requirement'),
        ),
    ]
